# -*- coding: utf-8 -*-
"""Data module that contains strings that mark the start and end of a Project
Gutenberg disclaimer/header."""


from six import u


TEXT_START_MARKERS = frozenset((u(_) for _ in (
    "*END*THE SMALL PRINT",
    "*** START OF THE PROJECT GUTENBERG",
    "*** START OF THIS PROJECT GUTENBERG",
    "This etext was prepared by",
    "E-text prepared by",
    "Produced by",
    "Distributed Proofreading Team",
    "Proofreading Team at http://www.pgdp.net",
    "http://gallica.bnf.fr)",
    "      http://archive.org/details/",
    "http://www.pgdp.net",
    "by The Internet Archive)",
    "by The Internet Archive/Canadian Libraries",
    "by The Internet Archive/American Libraries",
    "public domain material from the Internet Archive",
    "Internet Archive)",
    "Internet Archive/Canadian Libraries",
    "Internet Archive/American Libraries",
    "material from the Google Print project",
    "*END THE SMALL PRINT",
    "***START OF THE PROJECT GUTENBERG",
    "This etext was produced by",
    "*** START OF THE COPYRIGHTED",
    "The Project Gutenberg",
    "http://gutenberg.spiegel.de/ erreichbar.",
    "Project Runeberg publishes",
    "Beginning of this Project Gutenberg",
    "Project Gutenberg Online Distributed",
    "Gutenberg Online Distributed",
    "the Project Gutenberg Online Distributed",
    "Project Gutenberg TEI",
    "This eBook was prepared by",
    "http://gutenberg2000.de erreichbar.",
    "This Etext was prepared by",
    "This Project Gutenberg Etext was prepared by",
    "Gutenberg Distributed Proofreaders",
    "Project Gutenberg Distributed Proofreaders",
    "the Project Gutenberg Online Distributed Proofreading Team",
    "**The Project Gutenberg",
    "*SMALL PRINT!",
    "More information about this book is at the top of this file.",
    "tells you about restrictions in how the file may be used.",
    "l'authorization à les utilizer pour preparer ce texte.",
    "of the etext through OCR.",
    "*****These eBooks Were Prepared By Thousands of Volunteers!*****",
    "We need your donations more than ever!",
    " *** START OF THIS PROJECT GUTENBERG",
    "****     SMALL PRINT!",
    '["Small Print" V.',
    '      (http://www.ibiblio.org/gutenberg/',
    'and the Project Gutenberg Online Distributed Proofreading Team',
    'Mary Meehan, and the Project Gutenberg Online Distributed Proofreading',
    '                this Project Gutenberg edition.',
    "Online Distributed Proofreading Team at http://www.pgdp.net",
    "(This file was produced from images generously made",
    "Proofreading Team.",
    "produced from scanned images of public domain material",
    "file was produced from images generously made available",
    "from the Google Print project.)",
    "Libraries.)",
    "Proofreaders",
    "generously made available by The Internet Archive/American",
    "and the Online Distributed Proofreading Team.",
    "Proofreading Team",
    "Online Distributed Proofreading Team",
    "generously made available by The Internet Archive)",
    "Online Distributed Proofreading Team (http://www.pgdp.net)",
    "generously made available by the Bibliothèque nationale",
    "produced from images available at The Internet Archive)",
    "Online Distributed Proofreading Team at http://www.pgdp.net.",
    "Distributed Proofreaders",
    "Online Distributed Proofreading Team.",
    "Proofreading Team (http://www.pgdp.net) from page images generously made",
    "de France (BnF/Gallica) at http://gallica.bnf.fr)",
    "(http://www.archive.org/details/americana)",
    "generously made available by The Internet Archive.)",
    "produced from images generously made available by The",
    "available by The Internet Archive/American Libraries.)",
    "available by The Internet Archive)",
    "(http://www.pgdp.net)",
    "generously made available by The Internet Archive/Canadian",
    "available by the Bibliothèque nationale de France",
    "provided by the Internet Archive",
    "Team at http://www.pgdp.net (This file was produced from",
    "Libraries)",
    "by the Bibliothèque nationale de France (BnF/Gallica)",
    "Distributed Proofreaders Europe at http://dp.rastko.net.",
    "This file was produced from images generously made available",
    "Team at http://www.pgdp.net",
    "of public domain material from Google Book Search)",
    "generously made available by The Internet Library of Early",
    "and the Online Distributed Proofreading Team",
    "project.)",
    "Journals.)",
    "images of public domain material from the Google Print",
    "state of Mississippi and granted tax exempt status by the Internal",
    "501(c)(3) educational corporation organized under the laws of the",
    "at http://www.pgdp.net",
    "Revenue Service.  The Foundation's EIN or federal tax identification",
    "Transcriber's note:",
    "Internet Archive.)",
    "images generously made available by The Internet",
    "produced from images generously made available by the",
    "images generously made available by The Internet Archive)",
    "produced from images generously made available by National",
    "generously made available by Internet Archive/American Libraries",
    "Gutenberg.",
    "Proofreading Team (http://www.pgdp.net)",
    "available by Internet Archive (https://archive.org)",
    "scanned images of public domain material from the Google",
    "by The Kentuckiana Digital Library)",
    "Gutenberg (This file was produced from images generously",
    "Library of Portugal (Biblioteca Nacional de Portugal).)",
    "http://www.pgdpcanada.net",
    "available by The Internet Archive/Canadian Libraries)",
    "Online Distributed Proofreaders Europe at",
    "Online Distributed Proofreading Team (http://www.pgdp.net/)",
    "(This book was produced from scanned images of public",
    "(http://digital.library.villanova.edu/))",
    "Distributed Proofreading Canada Team at",
    "made available by The Internet Archive/American Libraries.)",
    "http://www.freeliterature.org (Images generously made",
    "http://gallica.bnf.fr.",
    "domain material from the Google Print project.)",
    "Proofreading Team. This file was produced from images generously",
    "http://dp.rastko.net. This file was produced from images",
    "Print archive.",
    "Team (http://www.pgdp.net) from page images generously made available by",
    "the Online Distributed Proofreading Team.",
    "by The Internet Library of Early Journals.)",
    "page images supplied by the Universal Library Project",
    "at Carnegie Mellon University.",
    "and the Online Distributed Proofreading team, using",
    "Internet Archive (https://archive.org)",
    "Team",
    "Online Distributed Proofreading Team (http://www.pgdp.net) from page",
    "made available by the Bibliothèque nationale de France (BnF/Gallica)",
    "Team (http://www.pgdp.net)",
    "This file was produced from images generously made available by The",
    "the Online Distributed Proofreading Team",
    "Proofreading Team. HTML version by Al Haines.",
    "http://www.pgdpcanada.net (This file was produced from",
    "available by Internet Archive/American Libraries",
    "(http://www.pgdp.net) from page images generously made available by",
    "(http://www.archive.org/details/toronto)",
    "Team.",
    "produced by Microsoft for their Live Search Books site.)",
    "available by Biblioteca Nazionale Braidense - Milano)",
    "a team of about twenty Project Gutenberg volunteers.",
    "images generously made available by the Bibliothèque",
    "at http://www.pgdp.net (This file was produced from images",
    "Proofreaders Europe.",
    "file was produced from scans of public domain material",
    "by the Canadian Institute for Historical Microreproductions",
    "(www.canadiana.org))",
    "generously made available by Internet Archive (https://archive.org)",
    "Archive.",
    "available by the Internet Archive.)",
    "Kentuckiana Digital Library)",
    "(https://archive.org/details/americana)",
    "by the Bibliothèque nationale de France (BnF/Gallica) at",
    "http://gallica.bnf.fr",
    "Archive/American Libraries.)",
    "of the Digital Library@Villanova University",
    "(http://www.pgdp.net/)",
    "This file was produced from images generously made available by the",
    "Proofreading Team at DP Europe (http://dp.rastko.net)",
    "produced from images made available by the HathiTrust",
    "Digital Library.)",
    "available by Cornell University Digital Collections.)",
    "and PG Distributed Proofreaders",
    "Proofreading Canada Team at http://www.pgdpcanada.net",
    "Proofreaders. This file was produced from images generously made",
    "file was produced from images produced by Core Historical",
    "scanned images of public domain material from the Internet",
    "(Images generously made available by the Internet Archive.)",
    "courtesy of the Digital Library@Villanova University",
    "Mobipocket Reader format, eReader format and Acrobat Reader format.",
    "public domain works from the University of Michigan Digital",
    "Literature in Agriculture (CHLA), Cornell University)",
    "produced from scans of public domain material produced by",
    "Microsoft for their Live Search Books site.)",
    "Internet Archive (http://www.archive.org)",
    "available by Cornell University Digital Collections)",
    "version by Al Haines.",
    "Team. This file was produced from images generously made available",
    "nationale de France (BnF/Gallica) at http://gallica.bnf.fr.",
    "(http://kdl.kyvl.org/)",
    "Mississippi and granted tax exempt status by the Internal Revenue Service.",
    "generously made available by the Bibliothèque nationale de France",
    "by the Bibliothèque nationale de France (BnF/Gallica))",
    "501(c)(3) educational corporation organized under the laws of the state of",
    "Online Distributed Proofreading Canada Team at",
    "available by the Canadian Institute for Historical",
    "Charles Franks and the Online Distributed Proofreading Team.",
    "Bibliothèque nationale de France (BnF/Gallica) at",
    "Bibliothèque nationale de France (BnF/Gallica)",
    "P. Travers and the Online Distributed Proofreading Team",
    "(http://books.google.com)",
    "file was produced from scans of public domain works at the",
    "The Foundation’s EIN or federal tax identification number is 64-6221541.",
    "is available at http://www.ebooksgratuits.com in Word format,",
    "by The Internet Archive.)",
    "available by The Internet Archive.)",
    "available by Internet Archive (http://www.archive.org)",
    "and David Widger  <widger@cecomet.net>",
    "public domain material from the Google Print project.)",
    "Proofreaders Europe at http://dp.rastko.net. This file was",
    "images generously made available by Internet Archive (https://archive.org)",
    "(http://www.freeliterature.org) from page images generously made available",
    "generously made available by Internet Archive (http://www.archive.org)",
    "Franks and the Online Distributed Proofreading Team.",
    "University of Michigan's Making of America collection.)",
    "the Online Distributed Proofreading Team (http://www.pgdp.net) from page",
    "images generously made available by Internet Archive/American Libraries",
    "Gutenberg (This book was produced from scanned images of",
    "http://www.freeliterature.org",
    "by Linda Cantoni.",
    "available by Cornell University Digital Collections).",
    "at http://www.freeliterature.org (From images generously",
    "(http://www.archive.org)",
    "generously made available by the Google Books Library Project",
    "generously made available by the Canadian Institute for",
    "***",
    "Proofreading Team at http://www.fadedpage.net",
    "Proofreaders Europe. This file was produced from images generously",
    "Malcolm Farmer and the Online Distributed Proofreading",
    "generously made available by Internet Archive/Canadian Libraries",
    "Distributed Proofreaders Canada team at",
    "and revised by Joseph E. Loewenstein, M.D.",
    "Online Distributed Proofreading Team (http://www.pgdp.net) from digital",
    "Libraries (http://www.archive.org/details/toronto)",
    "(http://link.library.utoronto.ca/booksonline/).)",
    "was produced from images generously made available by the Bibliothèque",
    "Transcribed from the 1913 Thomas J. Wise pamphlet by David Price, email",
    "Mormon texts available on Project Gutenberg, to help",
    "Internet Archive.",
    "International Children's Digital Library.)",
    "Digital & Multimedia Center, Michigan State University",
    "by Cornell University Digital Collections)",
    "available by the Google Books Library Project (http://books.google.com)",
    "available by the Bibliothèque nationale de France (BnF/Gallica) at",
    "provided by Google Books",
    "http://mormontextsproject.org/ for a complete list of",
    "file was made using scans of public domain works in the",
    "Distributed Proofreaders Europe at http://dp.rastko.net",
    "by Al Haines.",
    "Archive/Children's Library)",
    "was produced from images generously made available by the",
    "the Online Distributed Proofreading Team (http://www.pgdp.net)",
    "[Project Gutenberg is a TradeMark and may not be used in any sales",
    "produced from images available at the Bibliothèque nationale",
    "[Portions of this header are copyright (C) 2001 by Michael S. Hart",
    "nationale de France (BnF/Gallica) at http://gallica.bnf.fr)",
    "made available by the University of Toronto Libraries",
    "made available by the Bibliotheque nationale de France (BnF/Gallica)",
    "(Images generously made available by the Internet Archive)",
    "(http://www.pgdp.net) from page images generously made available by the",
    "http://www.freeliterature.org (From images generously made",
    "Franks and the Online Distributed Proofreading Team",
    "by The University of Florida, The Internet",
    "by the Canadian Institute for Historical Microreproductions.",
    "and may be reprinted only when these Etexts are free of all fees.]",
    "This ebook was transcribed by Les Bowler.",
    "Proofreading Team.(www.pgdp.net)",
    "Proofreaders Team",
    "Nous remercions la Bibliothèque Nationale de France qui a mis à",
    "nationale de France (BnF/Gallica)",
    "made available by the Internet Archive.)",
    "http://www.eBookForge.net",
    "(http://posner.library.cmu.edu/Posner/))",
    "HathiTrust Digital Library.)",
    "Google Books (Oxford University)",
    "from the Internet Archive.)",
    "book was created from images of public domain material",
    "(BnF/Gallica) at http://gallica.bnf.fr.",
    "available in multiple formats at www.ebooksgratuits.com",
    "at http://gallica.bnf.fr.",
    "provided by The Internet Archive",
    "Library)",
    "Gutenberg",
    "generously made available by the BibliothÃ¨que nationale",
    "from images generously made available by the Bibliothèque",
    "format, eReader format and Acrobat Reader format.",
    "de France (BnF/Gallica) at http://gallica.bnf.fr.",
    "Canadian Institute for Historical Microreproductions.",
    "book was produced from images made available by the",
    "(BnF/Gallica) at http://gallica.bnf.fr",
    "available by the Internet Archive)",
    "available at http://www.ebooksgratuits.com",
    "University of Michigan.",
    "University of Georgia.)",
    "Transcribed by David Price, email ccx074@coventry.ac.uk",
    "Team at http://www.pgdp.net.",
    "Proofreading Team (http://www.pgdp.net).",
    "Proofreading Team, and The Internet Library of Early Journals",
    "Proofreading Canada Team at http://www.pgdpcanada.net (This",
    "produced from images generously made available by Cornell",
    "Online Distributed Proofreading Team (http://www.pgdp.net/) from page",
    "Online Distributed Proofreading Team (http://www.pgdp.net/c/)",
    "Libraries (http://www.archive.org/details/americana)",
    "(http://www.pgdp.net/c/)",
    "http://www.bibliotecaitaliana.it/ScrittoriItalia)",
    "http://dp.rastko.net",
    "Historical Microreproductions (www.canadiana.org))",
    "globaltraveler5565@yahoo.com.",
    "file made using scans of public domain works at the",
    "disponibilizada pela bibRIA.",
    "credit",
    "at http://www.ebooksgratuits.com in Word format, Mobipocket Reader",
    "at http://gallica.bnf.fr",
    "www.history-matters.com.",
    "This eBook was produced by Tapio Riikonen",
    "This eBook was produced by David Widger",
    "proofread similar books, or to report typos.",
    "Proofreading Team at www.pgdp.net.",
    "Proofreaders. Produced from page scans provided by Cornell University.",
    "Proofreaders.",
    "material generously made available by Internet Archive/American Libraries",
    "made available by The Internet Archive/Canadian Libraries)",
    "Library.)",
    "(http://books.google.com/)",
    "Distributed Proofreading Canada Team (http://www.pgdpcanada.net)",
    "by the Library of Congress)",
    "Boissonnas, The Internet Archive for some images and the",
    "visite http://pt-scriba.blogspot.com/ (This book was",
    "University Digital Collections)",
    "University, and Alev Akman",
    "public domain works in the International Children's Digital",
    "Proofreading Team at www.pgdp.net",
    "produced by Core Historical Literature in Agriculture",
    "page images generously made available by Early Canadiana Online",
    "Microreproductions",
    "Internet Archive",
    "images generously made available by Internet Archive/Canadian Libraries",
    "(http://dp.rastko.net); produced from images of the",
    "Haines.",
    "Gutenberg. (This file was produced from images generously",
    "Fraser-Cunliffe and the Online Distributed Proofreading",
    "Distributed Proofreaders. Produced from page scans provided by",
    "by the Posner Memorial Collection",
    "by The Kentuckiana Digital Library.)",
    "by the Bibliothèque nationale de France (BnF/Gallica).",
    "Bibliothèque nationale de France (BNF/Gallica) at",
    "available by The Internet Archive/American Libraries.",
    "available by Biblioteca Nazionale Braidense - Milano at",
    "Archive",
    "(This file was made using scans of public domain works",
    "Proofreading volunteers at http://www.pgdp.net for Project",
    "Library of Congress)",
    "images generously made available by the Google Books Library Project",
    "(http://www.freeliterature.org)",
    "Google Books Library Project (http://books.google.com)",
    "from the University of Michigan Digital Libraries.)",
    "from images provided by the Million Book Project.",
    "From images generously made available by Gallica",
    "France (BnF/Gallica) at http://gallica.bnf.fr)",
    "Digital Library Project at http://www.tpdlp.net and the",
    "(CHLA), Cornell University)",
    "by Internet Archive (https://archive.org)",
    "by Case Western Reserve University Preservation Department",
    "and David Widger [widger@cecomet.net]",
    "American Fiction Project.)",
    "the Biblioteca Italiana at",
    "online Distributed Proofreaders Canada team at",
    "made available by The Internet Archive.)",
    "made available by Editore Laterza and the Biblioteca",
    "Library of Congress, Manuscript Division)",
    "Italiana at",
    "Internet Archive/Million Book Project)",
    "images generously made available by Kentuckiana Digital Library",
    "(Images generously made available by Editore Laterza and",
    "http://www.ebooksgratuits.com",
    "Google Books (Harvard University)",
    "generously made available by the Digital & Multimedia",
    "generously made available by Kentuckiana Digital Library",
    "Ernest Schaal, and the Online Distributed Proofreading",
    "Distributed Proofreaders.",
    "dispositions les images dans www://gallica.bnf.fr, et a donné",
    "Digital Library)",
    "de France (BnF/Gallica)",
    "Charles Franks and the Online Distributed Proofreading",
    "Center, Michigan State University Libraries.)",
    "by The Internet Archive",
    "book was produced from scanned images of public domain",
    "(BnF/Gallica)",
    "Blenkinship and the Online Distributed Proofreading Team",
    "available by the Bibliotheque nationale de France (BnF/Gallica) at",
    "at http://www.eBookForge.net",
    "Viswanathan, and the Online Distributed Proofreading Team",
    "(This file was produced from images produced by Core",
    "(This file was made using scans of public domain works in",
    "This eBook was produced by Andrew Heath",
    "the International Children's Digital Library.)",
    "Team at http://www.pgdp.net (This book was produced from",
    "(Stanford University, SUL Books in the Public Domain)",
    "public domain material generously made available by the Google Books",
    "Provided by McGuinn's Folk Den (http://www.ibiblio.org/jimmy/folkden)",
    "Proofreading Team at DP Europe (http://dp.rastko.net);",
    "(Produced from images of the Bibliothèque nationale de",
    "PG Online Distributed Proofreading Team.",
    "PG Distributed Proofreaders",
    "page images generously made available by Internet Archive/Canadian",
    "page images generously made available by Internet Archive",
    "Online Distributed Proofreading Team. HTML version by Al",
    "Online.)",
    "Library Project (http://books.google.com/)",
    "images generously made available by the CWRU Preservation",
    "images generously made available by Internet Archive",
    "http://dp.rastko.net.",
    "(http://dp.rastko.net)",
    "Historical Literature in Agriculture (CHLA), Cornell",
    "generously made available by the Bibliotheque nationale de France",
    "from images generously made available by the Bibliotheque nationale",
    "Franks, and the Online Distributed Proofreading Team",
    "file was made using scans of public domain works from the",
    "Europe at http://dp.rastko.net. This file was produced",
    "Edkins and the Online Distributed Proofreading Team.",
    "Distributed Proofreaders. This file was produced from images generously",
    "Charles Franks and the Online Distributed Proofreading Team",
    "by The Internet Archive/Million Book Project)",
    "by Cornell University Digital Collections.)",
    "by Biodiversity Heritage Library.)",
    "available by Internet Archive/Canadian Libraries",
    "Archive/Canadian Libraries)",
    "and the PG Online Distributed Proofreading Team.",
    "and the Online Distributed Proofreading Team. This file",
    "and the Online Distributed Proofreading Team. HTML version",
    "and Project Gutenberg Distributed Proofreaders",
    "Wayne Hammond and the Online Distributed Proofreading Team",
    "University of Michigan Digital Libraries.)",
    "Sutherland and the Online Distributed Proofreading Team",
    "Revenue Service. The Foundation's EIN or federal tax identification",
    "public domain material from Google Book Search)",
    "Proofreading Team. (www.pgdp.net)",
    "Proofreading Team at http://www.pgdpcanada.net",
    "Proofreaders Europe, http://dp.rastko.net.  This file was produced",
    "Proofreaders Europe at http://dp.rastko.net",
    "Proofreaders Europe",
    "produced from images produced by Core Historical Literature",
    "Print project.",
    "page images generously made available by Internet Archive/American",
    "Online Distributed Proofreading Team (www.pgdp.net)",
    "Microreproductions.",
    "Loewenstein, M.D.",
    "Lesley Halamek and the Online Distributed Proofreading",
    "in Agriculture (CHLA), Cornell University)",
    "(http://www.canadiana.org/eco/index.html)",
    "(https://archive.org/details/toronto)",
    "(http://mormontextsproject.org/)",
    "from scans of public domain material at Austrian Literature",
    "from images generously made available by The Internet Archive/American",
    "Franks and the Online Distributed Proofreading Team. This",
    "Europe at http://dp.rastko.net",
    "digital material generously made available by the Internet",
    "digital material generously made available by Internet Archive/Canadian",
    "digital material generously made available by Internet Archive/American",
    "created from images of public domain material made available",
    "by the University of Toronto Libraries",
    "available by The Kentuckiana Digital Library)",
    "available by the Internet Archive and the University of",
    "at http://www.pgdp.net.",
    "and the Online Distributed Proofreading Team (http://www.pgdp.net)",
    "Al Haines.",
    "Web Archive (University of Illinois Urbana-Champaign)",
    "transcribed by Veronika Redfern.",
    "transcribed by June Troyer.",
    "(This file was produced from images produced by the Wright",
    "the Online Distributed Proofreading Team. HTML version by",
    "the Online Distributed Proofreading Canada Team at",
    "Team from images provided by the Million Book Project",
    "Rita Farinha and the Online Distributed Proofreading Team",
    "proofread similar books, or to report typos. Special thanks",
    "Proofreading Team at http://www.fadedpage.com",
    "Proofreading Team and The Internet Library of Early Journals,",
    "Proofreading Team and The Internet Library of Early Journals",
    "Proofreading Team!",
    "produced from scanned images of public domain material at",
    "Online Distributed Proofreading Team of Europe. This file",
    "Online Distributed Proofreading Team at http://www.pgdp.net/",
    "Online Distributed Proofreaders",
    "material generously made available by the Google Books Library Project",
    "made available by the Internet Archive)",
    "made available by the Canadian Institute for Historical",
    "made available by the Bibliothèque nationale de France (BnF/Gallica).",
    "      Images of the original pages are available through the Florida",
    "images generously made available by the Canadian Institute",
    "images generously made available by the Bibliothèque nationale de",
    "(http://mormontextsproject.org)",
    "(http://digital.library.villanova.edu)",
    "generously made available by the Library of Congress)",
    "generously made available by Biblioteca Nazionale Braidense",
    "from images provided by the Library of Congress, Manuscript Division.",
    "from images generously made available by The Internet",
    "file is gratefully uploaded to the PG collection in honor",
    "Distributed Proofreaders Team",
    "Distributed Proofreaders from images generously made",
    "Canadian Institute for Historical Microreproductions",
    "by the Internet Archive",
    "by the Bibliotheque nationale de France (BnF/Gallica) at",
    "Brown and the Online Distributed Proofreading Team.",
    "Boissonnas and the Online Distributed Proofreading Team",
    "      Board of Education, Division of Colleges and Universities,",
    "Bibliothèque nationale de France (BnF/Gallica) at http://gallica.bnf.fr.",
    "(Bibliothèque nationale de France) at http://gallica.bnf.fr.",
    "available by Biblioteca Sormani - Milano)",
    "at http://www.pgdp.net (This book was produced from scanned",
    "at http://www.ebooksgratuits.com.",
    "and the Project Gutenberg Online Distributed Proofreading",
    "Women Working 1800 - 1930)",
    "We need more volunteers like you.  Learn more at http://runeberg.org/",
    "the Online Distributed Proofreaders Europe at",
    "the Google Books Library Project (http://books.google.com)",
    "the Digital Library of the Falvey Memorial Library, Villanova University",
    "Team (http://www.pgdp.net) from digital material generously made available",
    "Team at http://www.pgdp.net (This file was produced from images",
    "public domain material made available by Google Books.",
    "Proofreaders. Produced from page scans provided by University of",
    "Proofreaders. Produced from page scans provided by Internet Library",
    "      Project Gutenberg has the other two volumes of this work.",
    "Project Gutenberg.",
    "produced from images of the Bibliothèque nationale de",
    "produced by the Wright American Fiction Project.)",
    "Print project.)",
    "pagpapahalaga ng panitikang Pilipino.",
    "Online Distributed Proofreading Team. This file was produced",
    "Online Distributed Proofreaders Team",
    "of public domain material from BibRia)",
    "of Early Journals.",
    "of Distributed Proofreaders having posted over 10,000",
    "ng Proyektong Gutenberg ng Pilipinas para sa pagpapahalaga",
    "ng panitikang Pilipino. (http://www.gutenberg.ph)",
    "- Milano)",
    "Michigan.",
    "memory of Steven Gibbs (1938-2009).",
    "Martin Pettit and the Online Distributed Proofreading Team",
    "Lisa Reigel, and the Online Distributed Proofreading Team",
    "images generously made available by the Digital & Multimedia",
    "Hutchinson, and the Project Gutenberg Online Distributed Proofreading Team",
    "(http://www.canadiana.org)",
    "http://dp.rastko.net. (This file was made using scans of",
    "http://bencrowder.net/books/mtp. Volunteers: Benjamin",
    "HTML version by Al Haines.",
    "Gutenberg Projekt-DE.",
    "generously made available by The Kentuckiana Digital",
    "Garcia and the Online Distributed Proofreading Team.",
    "from scanned images of public domain material from the Google Print",
    "Franks and the Distributed Proofreaders Team",
    "France (BNF/Gallica) at http://gallica.bnf.fr",
    "for Historical Microreproductions.",
    "file was produced from images produced by the Wright",
    "file was made using scans of public domain works put online",
    "ebooks.",
    "Distributed Proofreaders. This file was produced from images",
    "Distributed Proofreaders. This file was produced from",
    "disposition les images dans www://gallica.bnf.fr, et a donné",
    "digital material generously made available by Internet Archive",
    "Credit",
    "by the University of Florida Digital Collections.)",
    "by the Internet Archive: American Libraries",
    "by Internet Archive (http://www.archive.org)",
    "by Internet Archive/American Libraries",
    "by HathiTrust Digital Library (http://www.hathitrust.org/digital_library)",
    "by Biblioteca Sormani - Milano)",
    "(BnF/Gallica).",
    "available by The Internet Archive/Canadian Libraries.)",
    "available by the Hathi Trust)",
    "available by the Canadian Institute for Historical Microreproductions.",
    "available by gallica (Bibliotheque nationale de France) at",
    "available at http://www.ebooksgratuits.com in Word format,",
    "at http://www.ebooksgratuits.com",
    "Archive.)",
    "and the Online Distributed Proofreading Team at http://www.pgdp.net",
    "and the Online Distributed Proofreading Canada Team at",
    "and the Distributed Proofreading Team",
    "and Fred); this text is also available at",
    "All of the original Project Gutenberg Etexts from the",
    "Aldarondo, Charles Franks and the Online Distributed",
    "Wheaton, and the Online Distributed Proofreading Team (http://www.pgdp.net)",
    "We are planning on making some changes in our donation structure",
    "visite http://pt-scriba.blogspot.com/ (produzido a partir",
    "University of Florida, The Internet Archive/Children's",
    "University, Alev Akman, and Dianne Bean",
    "Transcriber's Note:",
    "This etext was created by Charles Aldarondo (Aldarondo@yahoo.com).",
    "the original was typed in (manually) twice and electronically compared.",
    "The Foundations EIN or federal tax identification number is 64-6221541.",
    "Team. Text version by Al Haines.",
    "Team (http://www.pgdp.net/)",
    "Steve Schulze and the Online Distributed Proofreading Team",
    "Staatsbibliothek / Bavarian State Library.)",
    "scanned images of public domain material generously made available by the",
    "Rénald Lévesque and the Online Distributed Proofreaders",
    "Proofreading Team from images generously made available by the",
    "Proofreading Team at http://dp.rastko.net",
    "Proofreaders. HTML version by Al Haines.",
    "Projects, Mary Meehan, and the Project Gutenberg Online Distributed",
    "      Project Gutenberg has the other volumes of this work.",
    "Project by Riikka Talonpoika and Tapio Riikonen",
    "Project by Carlo Traverso, revision by Claudio Paganelli.",
    "produced from scans of public domain works at the University",
    "Preservation Department Digital Library)",
    "Post-Processor and the Project Gutenberg Online Distributed",
    "Pilar Somoza and PG Distributed Proofreaders from page",
    "Pfister-Altschul and the Online Distributed Proofreading",
    "pela Biblioteca Nacional de Portugal - This file was",
    "Paolucci and the Online Distributed Proofreading Team.",
    "page images generously made available by the Internet",
    "page images generously made available by Kentuckiana Digital Library",
    "Online Distributed Proofreading Team from page images generously made",
    "Online Distributed Proofreading Team at www.pgdp.net",
    "Online Distributed Proofreading",
    "online book collection (http://www.hti.umich.edu/m/moa/).",
    "of Michigan's Making of America collection.)",
    "nationale de France (BnF/Gallica) at http://gallica.bnf.fr",
    "(MormonTextsProject.org).",
    "(MormonTextsProject.org)",
    "material generously made available by Internet Archive/Canadian Libraries",
    "material generously made available by Internet Archive",
    "material from the Google Books project.",
    "material from the Google Book Search project.)",
    "Mary Meehan and the Online Distributed Proofreading Team",
    "made available by the HathiTrust Digital Library.)",
    "made available by the Bibliotheque nationale de France (BnF/Gallica).",
    "made available by the Biblioteca Nacional de Lisboa, Portugal.",
    "Literature in Agriculture (CHLA), Cornell University.)",
    "Library of Early Journals.",
    "Learn more at =http://runeberg.org/=",
    "Jonathan Ingram and the Online Distributed Proofreading",
    "Internet Archive (http://www.archive.org/)",
    "in cooperation with Progetto Manuzio, http://www.liberliber.it",
    "in 2000, so you might want to email me, hart@pobox.com beforehand.",
    "images produced by Core Historical Literature in Agriculture",
    "images of public domain material from the Google Books",
    "images generously made available by the Kentuckiana Digital Library",
    "(Images generously made available by the Internet Archive",
    "images generously made available by The Internet Archive",
    "(Images generously made available by the Hathi Trust)",
    "images generously made available by Bayerische",
    "(http://www.pgdp.net).",
    "(http://www.hathitrust.org/digital_library)",
    "(http://www.freeliterature.org) from page mages generously made available",
    "http://www.fadedpage.net",
    "http://www.fadedpage.com",
    "(http://www.archive.org/details/toronto), Suzanne Lybarger,",
    "(https://archive.org)",
    "(http://digital.library.villanova.edu/)",
    "(http://bnd.bn.pt).",
    "Historical Microreproductions.",
    "HathiTrust Digital Library (http://www.hathitrust.org/digital_library)",
    "generously made available by National Library of Portugal",
    "generously made available by Early Canadiana Online",
    "generously made available by Cornell University Digital",
    "generously made available by Case Western Reserve University",
    "generously made available by Arkiv for Dansk Litteratur",
    "from page images generously made available by Internet Archive",
    "(From images generously made available by the Internet",
    "France (BnF/Gallica) at http://gallica.bnf.fr.",
    "Ernest Schaal and the Online Distributed Proofreading Team",
    "DP Team",
    "Distributed Proofreading team at DP-test Italia.",
    "Distributed Proofreading Canada Team (http://www.pgdpcanada.net) from page",
    "Department Digital Library",
    "Dave Morgan and the Online Distributed Proofreading Team",
    "das imagens de obras em domínio público, disponibilizadas",
    "Copyright (c) 2003 by John Moncure Wetterau",
    "Coolmicro and Fred); this text is also available at",
    "Charles Franks and Distributed Proofers.",
    "by the Million Book Project.",
    "by The Internet Archive.",
    "by the Bodleian Libraries, University of Oxford",
    "Brown and PG Distributed Proofreaders",
    "(BnF/Gallica) at http://gallica.bnf.fr)",
    "Bibliothèque Nationale de France at http://gallica.bnf.fr; this text is",
    "Ball and the Online Distributed Proofreading Team.",
    "available by Villanova University Digital Library",
    "available by The Internet Archive/Million Book Project)",
    "available by the Hathi Trust.)",
    "available by the BibliothÃ¨que nationale de France",
    "available by Case Western Reserve University Preservation",
    "at http://www.freeliterature.org",
    "at http://dp.rastko.net. This file was produced from images",
    "at http://adl.dk)",
    "Archive: Research, Tradition and History, Albert R. Mann",
    "Archive: American Libraries, and Project Gutenberg Australia",
    "Archive: American Libraries.",
    "Archive)",
    "a partir da digitalização do original, disponibilizada",
    "and the Online Distributed Proofreading Team, from images",
    "and the Online Distributed Proofreaders Europe at",
    "and the distributed proofers. HTML version by Al Haines.",
    "also available at http://www.ebooksgratuits.com in Word format,",
    "alight@mercury.interpath.net, etc.).  To assure a high quality text,",
    "William Flis, and the Project Gutenberg Online Distributed Proofreading",
    "Web Archive and Google Books.",
    "Watch, Rockland, Maine, with technical assistance from Joseph E.",
    "was produced from images generously made available by",
    "     (University of Illinois Urbana-Champaign)",
    "University Library via www.sagnanet.is, Jóhannes Birgir",
    "University Libraries, Marilynda Fraser-Cunliffe, Sankar",
    "University.)",
    "transcribed by Linda Cantoni.",
    "to John B. Hare at www.sacred-texts.com",
    "(This file was produced from scans of public domain material",
    "(This file made from scans of public domain material at",
    "(This book was created from images of public domain material",
    "the PG Online Distributed Proofreading Team.",
    "the PG Online Distributed Proofreading Team",
    "the PG Online Distributed Proofreaders",
    "the PG collection in honor of Distributed Proofreaders",
    "Text Service of Indiana University",
    "Team. This file was produced from images generously made",
    "Team (http://www.fadedpage.net)",
    "Team (http://www.fadedpage.com)",
    "Team at www.pgdp.net.",
    "Team at http://www.pgdp.net. (This file was produced from",
    "Team at http://www.pgdpcanada.net",
    "Sutherland, Charles Franks and the Online Distributed",
    "Sutherland, and the Online Distributed Proofreading Team",
    "supplementation by David McClamrock",
    "scans provided by University of Michigan.",
    "(Scans generously made available by the Internet Archive",
    "scanned images of public domain material from The Internet",
    "Ribeiro, Larry Bergey and the Online Distributed",
    "public domain material from the Robinson Curriculum.)",
    "provided by University of Michigan.",
    "Proofreading Team (www.pgdp.net)",
    "Proofreading Team. The images for this file were generously",
    "Proofreading Team from images generously made available by gallica",
    "Proofreading Team, and The Internet Library of Early Journals,",
    "Proofreading Team, and Cornell University",
    "proofreading.",
    "Proofreaders. This file was produced from images generously",
    "Proofreaders. Produced from page scans provided by Biblioteca Nacional",
    "Proofreaders. Produced from page images provided by The Internet",
    "Proofreaders from page scans provided by University of Michigan.",
    "Proofreaders Europe, http://dp.rastko.net.",
    "Proofreaders Canada team at http://www.pgdpcanada.net",
    "produced from scanned images at The Internet Archive.)",
    "Produced from page scans provided by Cornell University.",
    "Produced from page images provided by Internet",
    "Produced from images provided by the Million Book Project.",
    "produced from images generously made available by Bielefeld",
    "produced from images generously made available by Biblioteca",
    "produced from images generously made available by",
    "produced from images available by The Internet Archive)",
    "produced from images available at The Internet",
    "produced from images available at the Digital & Multimedia",
    "Post-Processor; the PG Online Distributed Proofreaders Team",
    "Post-Processor, and the Project Gutenberg Online Distributed",
    "Portugal).)",
    "pela BibRIA - Biblioteca digital dos municipios da ria)",
    "Online Distributed Proofreading Team (http://www.pgdp.net) from scanned",
    "Online Distributed Proofreading Team from images generously made available",
    "Nuno Lopes (Projecto Enclave) and edited by Rita Farinha",
    "Note: Project Gutenberg also has an HTML version of this",
    "Nigel Blower and the Online Distributed Proofreading Team",
    "Nazionale Braidense - Milano)",
    "Music transcribed by Linda Cantoni.",
    "Matthew Wheaton and the Online Distributed Proofreading",
    "Mary Meehan and the Online Distributed Proofreading Team.",
    "Manuscript Division)",
    "made from images produced by the North Carolina History",
    "made available by gallica (Bibliothèque nationale de France) at",
    "made available by Biblioteca Nacional Digital",
    "Library of Portugal (Biblioteca Nacional de Portugal))",
    "Lévesque (HTML) and the Online Distributed Proofreaders",
    "Levesque and the Online Distributed Proofreading Team.",
    "Lévesque and the Online Distributed Proofreaders Europe",
    "Learn more at http://runeberg.org/",
    "King, and the Online Distributed Proofreading Team",
    "Juliet Sutherland, and the Online Distributed Proofreading",
    "Julia Neufeld and the Online Distributed Proofreading Team",
    "Journals.",
    "Josephine Paolucci and the Online Distributed Proofreading",
    "images provided by the Library of Congress, Manuscript Division.",
    "images of public domain material generously made available by the Google",
    "(Images generously provided by the Internet Archive.)",
    "(Images generously made available by the Internet Archive.]",
    "images generously made available by The Internet Archive.)",
    "(Images generously made available by the Hathi Trust.)",
    "images generously made available by JSTOR www.jstor.org)",
    "Hutchinson and the Online Distributed Proofreading Team.",
    "http://www.pgdpcanada.net. (This file was produced from",
    "(http://www.letrs.indiana.edu/web/w/wright2/) of the Library Electronic",
    "http://www.freeliterature.org (Scans generously made",
    "(http://www.archive.org/index.php)",
    "http://gallica.bnf.fr and The Internet Archive at",
    "http://gallica.bnf.fr.)",
    "(http://dp.rastko.net). This file was produced from images",
    "(http://books.google.com/intl/en/googlebooks/library.html)",
    "(http://archive.org/).",
    "(HTML version) and the Online Distributed Proofreaders",
    "H.P. Yarroll and the Online Distributed Proofreading Team",
    "Historical Microreproductions (www.canadiana.org).)",
    "having posted over 10,000 ebooks.",
    "Hans Pieterse and the Online Distributed Proofreading Team",
    "Gutenberg. (This book was produced from scanned images of",
    "Google Books (University of California)",
    "Google Books (the Bavarian State Library)",
    "generously provided by the Wright American Fiction Project",
    "generously made available by the Posner Memorial Collection",
    "generously made available by the Kentuckiana Digital Library",
    "generously made available by The Internet Archive/Canadian Libraries",
    "generously made available by The Internet Archive/American Libraries.)",
    "generously made available by Editore Laterza and the",
    "from the Google Print project)",
    "From images generously made available by gallica",
    "from Google Book Search)",
    "Franks and the Online Distributed Proofreaders Team",
    "for Project Gutenberg (This file was produced from images",
    "Flis, and the Online Distributed Proofreading Team.",
    "Europe, http://dp.rastko.net.  This file was produced from images",
    "Europe, http://dp.rastko.net",
    "Distributed Proofreaders. HTML version by Al Haines.",
    "digital.staatsbibliothek-berlin.de)",
    "Department Digital Library.",
    "de Lisboa.",
    "David Moynihan",
    "CWRU Preservation Department Digital Library",
    "Corrected and updated text and HTML PG Editions of the complete",
    "copyright laws for your country before downloading or redistributing",
    "Copyright laws are changing all over the world. Be sure to check the",
    "Collections and the Online Distributed Proofreading Team",
    "Collections)",
    "Charles Aldarondo and the Online Distributed Proofreading Team.",
    "Cantoni.",
    "Canada Team (http://www.pgdpcanada.net)",
    "by the Staatsbibliothek zu Berlin - PK,",
    "by the Library of Congress.)",
    "by the Kentuckiana Digital Library (http://kdl.kyvl.org/)",
    "by the Internet Archive.",
    "by the Google Books Library Project (http://books.google.com/)",
    "by the CWRU Preservation Department Digital Library",
    "by National Library of Portugal (Biblioteca Nacional de",
    "by Harvard University Library's Open Collections Program,",
    "by Google Books",
    "by gallica (Bibliothèque nationale de France) at http://gallica.bnf.fr",
    "by Biblioteca Nazionale Braidense - Milano)",
    "book was created from images provided by Bibliothèque et",
    "booksmiths at http://www.eBookForge.net",
    "(Biblioteca Nacional de Portugal).)",
    "Biblioteca Italiana at",
    "Bayerische Staatsbibliothek / Bavarian State Library.)",
    "available by The University of Florida, The Internet",
    "available by the Internet Archive.",
    "available by Internet Archive (https://archive.org/)",
    "available by gallica (Bibliothèque nationale de France) at",
    "Austrian Literature Online.)",
    "at http://gallica.bnf.fr.,",
    "AT gmail.com> and the Online Distributed Proofreading Team",
    "and the Online Distributed Proofreading Team at",
    "           and the Online Distributed Proofreading Team",
    "and the DP Team",
    "and Fiction Digital Library.)",
    "American Libraries)",
    "Adventure Continues and the Online Distributed Proofreading",
    "(1st-hand-history.org)",
    "You can get up to date donation information at:",
    "www.pgdp.net.",
    "www.canadiana.org",
    "(www.botanicus.org). and the Online Distributed Proofreading",
    "with the Online Distributed Proofreading Team of Charles Franks.",
    "with corrections or to participate in proofreading of",
    "We thank the \"Biblioteca Sormani\" di Milano that has provided the images.",
    "Western Reserve University Preservation Department Digital",
    "Weimar / Herzogin Anna Amalia Bibliothek.)",
    "Web Archive (University of Toronto)",
    "Web Archive (University of California Libraries)",
    "Web Archive (Oxford University)",
    "Web Archive (Harvard University)",
    "was produced from scanned images of public domain material",
    "Viswanathan and the Online Distributed Proofreading Team",
    "Viswanathan, and Distributed Proofreaders Europe at",
    "Virginia Library)",
    "University's Preservation Department",
    "University of Michigan\'s Making of America collection.)",
    "University of Glasgow.)",
    "University of Florida",
    "University, Millersville, PA, USA",
    "University Digital Collections.)",
    "University, Alev Akman, Dianne Bean, and Doris Ringbloom",
    "Transcriber's Notes:",
    "Transcribed from the early 1800's edition by David Price, email",
    "Transcribed from the 1889 Macmillan and Co. edition by David Price, email",
    "Transcribed from the 1858 William Tweedie edition by David Price, email",
    "Thomas Hutchinson and the Online Distributed Proofreading",
    "((This file was produced from images generously made",
    "(This file was produced from images from the Home Economics",
    "(This file was made using scans of public domain works put",
    "This eBook was transcribed by Les Bowler.",
    "This eBook was produced by Les Bowler, St. Ives, Dorset.",
    "the Wright American Fiction Project, Indiana University Digital Library",
    "the team of DP-Europe. (This file was produced from images",
    "the original book includes maps and other graphics.  These are",
    "the Online Distributed Proofreading Team at http://www.pgdp.net.",
    "the Online Distributed Proofreading Team at",
    "The Internet Archive/American Libraries.)",
    "The Internet Archive.)",
    "The Internet Archive.",
    "the Internet Archive.)",
    "the I.A. copy, was taken from Wikimedia Commons, where it",
    "the help in selecting and borrowing the books.",
    "the HathiTrust Digital Library (http://www.hathitrust.org/digital_library)",
    "the CIA's online version of the book published at the address:",
    "the 1890 George Bell and Sons edition.",
    "thanks to the Victorian Plays Project.",
    "thanks to Elmer Nocheseda for providing the material for",
    "Team. Produced from images provided by the Million Book Project",
    "Team. HTML version by Al Haines.",
    "Team from images provided by the Million Book Project.",
    "Steve Harris, Charles Franks and the Online Distributed Proofreading Team.",
    "State University Libraries.)",
    "site. Since 1997, PGCC had been working on gathering collections of",
    "similar early books of The Church of Jesus Christ of",
    "Shell, Charles Franks and the Online Distributed",
    "Search)",
    "Schulze and the Online Distributed Proofreading Team.",
    "scanned images of public domain material from Google Book",
    "scanned by Fox in the Stars from the collection of Brays",
    "Sächsische Landesbibliothek - Staats - und",
    "Roger DOMBRE ( pseud. of Mme Andrée SISSON née LIGEROT, 1859-",
    "Robert Rowe, Charles Franks and the Online Distributed Proofreading Team.",
    "que nationale de France (BnF/Gallica) at http://gallica.bnf.fr.",
    "Québec.)",
    "public domain material made available by the University",
    "public domain material from the Google Books project.)",
    "provided scans of missing pages for this book. (This book",
    "provided by the Million Book Project.",
    "provided by the Google Books",
    "provided by Google Books (Harvard College Library)",
    "provided by canadiana.org (http://www.canadiana.org/ECO/mtq?doc=34674)",
    "Proofreading Team. With special thanks to the library of",
    "Proofreading Team of Europe. This file was produced from",
    "Proofreading Team of Distributed Proofreaders Europe at",
    "Proofreading Team. Image files courtesy of gallica.bnf.fr.",
    "Proofreading Team (http://www.pgdp.net/) from page images generously made",
    "Proofreading Team from images provided by the Million Book Project",
    "Proofreading Team from images generously made available by the Canadian",
    "Proofreading Team. From images generously made available by gallica",
    "Proofreading Team Europe (http://dp.rastko.net)",
    "Proofreading Team at DP Europe (http://dp.rastko.net).",
    "Proofreading Team and Cornell University",
    "Proofreading Canada Team (http://www.pgdpcanada.net)",
    "proofreaders team.",
    "Proofreaders. Produced from Page Scans Provided by Cornell University.",
    "Proofreaders from images provided by Internet Archive Children's Library",
    "Proofreaders Europe team at http://dp.rastko.net",
    "Projects, Suzanne Lybarger, and the Project Gutenberg Online Distributed",
    "Project (http://books.google.com)",
    "Project Gutenbert Online Distributed Proofreading Team",
    "Project Gutenberg in 2003, and became an official Project Gutenberg",
    "Project Gutenberg",
    "Project by Carlo Traverso and Josette Harmelin",
    "Project by Carlo Traverso",
    "Project)",
    "Project.)",
    "Program (http://www.letrs.indiana.edu/web/w/wright2/)",
    "Produced from page scans provided by University of Michigan.",
    "Produced from images provided by The Internet Library of Early",
    "produced from images generously made available by SLUB:",
    "produced from images generously made available by Case",
    "produced from images available by The Internet Archive.)",
    "produced from images available at the Internet Archive.",
    "produced from images available at Bibliothèque nationale",
    "Post-Proofer; the Online Distributed Proofreaders Team",
    "Posner Memorial Collection",
    "Portugal.",
    "Pilar Somoza and PG Distributed Proofreaders. Para sa",
    "PG Online Distributed Proofreading Team",
    "PG Distributed Proofreaders Team",
    "PG Distributed Proofreaders from page scans provided by",
    "PG Distributed Proofreaders.",
    "Pécs, especially to the director, József Kereszturi for",
    "PDF format from the BNQ (Bibliothèque Nationale du Québec).",
    "Paolucci, and Project Gutenberg Distributed Proofreaders",
    "page images generously made available by the Kentuckiana Digital Library",
    "original copy of this book was generously made available",
    "Online Distributed Proofreading Team. This file was produced from",
    "Online Distributed Proofreading Team (http://www.pgdp.net/",
    "Online Distributed Proofreading Team Europe at",
    "Online Distributed Proofreading Team at www.pgdp.net.",
    "Online Distributed Proofreading Team at DP Europe",
    "Online Distributed Proofreading Canada Team (http://www.pgdpcanada.net)",
    "of Toronto Libraries",
    "of Toronto and the Online Distributed Proofreading Team",
    "of Florida.",
    "obtained from The Internet Archive.",
    "obtained from Gutenberg Projekt-DE.",
    "Norbert Müller and the Online Distributed Proofreading",
    "Nationale du Québec).",
    "(MormonTextsProject.org), with thanks to Renah Holmes for",
    "Melissa Er-Raqabi and the Online Distributed Proofreading",
    "Meehan, and Project Gutenberg Distributed Proofreaders",
    "M.D.",
    "Materials (PALMM))",
    "made available by the Kentuckiana Digital Library (http://kdl.kyvl.org/)",
    "made available by the Kentuckiana Digital Library",
    "made available by The Internet Archive)",
    "made available by the Digital & Multimedia Center, Michigan",
    "made available by Project Rastko.",
    "made available by Internet Archive.)",
    "Live Search Books site.)",
    "Linda Cantoni.",
    "Library, Cornell University)",
    "Library, and the Project Gutenberg Online Distributed Proofreading Team",
    "Library.",
    "Lesley Halamek, and the Online Distributed Proofreading",
    "Latter-Day Saints.",
    "Kurt Linack and Katrin Walter)",
    "Kirschner and the Project Gutenberg Online Distributed Proofreading Team",
    "Kirschner and PG Distributed Proofreaders",
    "Kentuckiana Digital Library.)",
    "Joseph E. Loewenstein, M.D.",
    "Jensson, Sankar Viswanathan, and the Online Distributed",
    "Jeannie Howse and the Online Distributed Proofreading Team",
    "Janet Blenkinship and the Online Distributed Proofreaders",
    "Internet Archive (https://archive.org/index.php)",
    "International Children's Digital Library (http://www.icdlbooks.org/)",
    "International Children's Digital Library (http://www.childrenslibrary.org/)",
    "Institute for Historical Microreproductions.",
    "Institute for Historical Microreproductions",
    "Initiatives and the Online Distributed Proofreading Team",
    "images provided by Bibliothèque et Archives nationales du",
    "(Images generously made available by the University of",
    "(Images generously made available by the Internet Archive,",
    "images generously made available by The Internet Archive).",
    "(Images generously made available by the Bodleian Library",
    "images generously made available by the Bibliothèque nationale de France",
    "images generously made available by Project Runeberg.",
    "images generously made available by National Library of",
    "images generously made available by HathiTrust Digital Library",
    "Hutchinson, and the Online Distributed Proofreading Team",
    "Hutchinson and the Online Distributed Proofreading Team",
    "Hungarian Distributed Proofreading Team (http://dphu.aladar.hu) from page",
    "http://www.sierraclub.org/john_muir_exhibit/",
    "(http://www.pgdp.net/) from page images generously made available by the",
    "(http://www.pgdp.net/) from page images generously made available by",
    "http://www.pgdpcanada.net This file was produced from",
    "http://www.pgdpcanada.net ((This file was produced from",
    "http://www.pgdpcanada.net. This document is available in",
    "http://www.pgdpcanada.net (This book was created from",
    "(http://www.pgdpcanada.net)",
    "http://www.odci.gov/cia/publications/factbook/guide.html  Note",
    "http://www.liberliber.it/",
    "http://www.liberliber.it",
    "(http://www.hti.umich.edu/m/moagrp/)",
    "(http://www.hti.umich.edu/m/moa/).",
    "http://www.freeliterature.org (Scans at the Internet",
    "http://www.fadedpage.net.",
    "(http://www.cervantesvirtual.com/)",
    "(http://www.canadiana.org/)",
    "(http://www.bodleian.ox.ac.uk/home)",
    "(http://www.archive.org/)",
    "(http:// mormontextsproject.org/)",
    "http://gallica.bnf.fr and The Internet Archive (American",
    "http://gallica.bnf.fr and by First-Hand History at",
    "http://dp.rastko.net. (This file was produced from images",
    "(http://dp.rastko.net). (This file was produced from images",
    "(http://dp.rastko.net/)",
    "http://bencrowder.net/books/mtp. Volunteers: Stephen",
    "http://bencrowder.net/books/mtp. Volunteers: Hilton",
    "(http://archive.org).",
    "Hodges, Charles Franks, and the Online Distributed",
    "Gutenberg the Online Distributed Proofreading Team (http://www.pgdp.net)",
    "Google Books (University of California, Davis)",
    "Google Books (the University of California)",
    "Google Books (New York Public Library)",
    "Google Books Library Project (http://books.google.com/)",
    "Google Books Library Project",
    "Google Books (Harvard College Library)",
    "Goodman, and Project Gutenberg Distributed Proofreaders",
    "generously made available by The Online Library of Liberty.)",
    "generously made available by the Library of Congress,",
    "generously made available by The Internet Archive/Million",
    "generously made available by The Internet Archive",
    "generously made available by the Canadian Institute for Historical",
    "generously made available by Internet Archive",
    "generously made available by Bnf-Gallica.)",
    "generously made available by Biodiversity Heritage Library.)",
    "generously made available by Biblioteca Sormani - Milano)",
    "from the Tartu University Library at http://www.utlib.ee)",
    "from the Google Print project and The Internet Archive.)",
    "from the 1911 John Murray edition.",
    "from scans of public domain material at Klassik Stiftung",
    "from images generously made available by The Internet Archive)",
    "from images generously made available by the Canadian",
    "Franks and the Online Distributed Proofreading Team. HTML",
    "Franks and the Online Distributed Proofreading Team, from",
    "France (http://gallica.bnf.fr/)",
    "France (BnF/Gallica)",
    "for scanning by the Department of Mathematics at the",
    "for proofreading.",
    "for Project Gutenberg. (This file was produced from images",
    "Florida.",
    "Flis, and the Online Distributed Proofreading Team",
    "file was produced from images of public domain material",
    "file was produced from images generously made available by the Biblioth",
    "file was produced from images generously made available by the",
    "file was produced from images from the Home Economics",
    "file was produced from images available at the Bibliothèque",
    "file was created from images generously made available by",
    "file includes images generously made available by The",
    "Europe, http://dp.rastko.net.",
    "Europe at http://dp.rastko.net.",
    "Europe at at http://dp.rastko.net",
    "E-mail - richardandmargie@mail.com",
    "E-mail: chrialex@myrealbox.com",
    "Edkins and the PG Online Distributed Proofreading Team.",
    "Editore Laterza and the Biblioteca Italiana at",
    "domain material from the Google Print project)",
    "domain images generously made available by the University",
    "Distributed Proofreading volunteers at http://www.pgdp.net",
    "Distributed Proofreaders Team at http://www.pgdp.net",
    "Distributed Proofreaders Europe team at http://dp.rastko.net",
    "Distributed Proofreaders Canada team (http://www.pgdpcanada.net)",
    "Digital Library project from the National Library of",
    "Digital Library, and Google.",
    "Digital--http://bnd.bn.pt).",
    "Digital Collections.)",
    "D'Hooghe at http://www.freeliterature.org (Images generously",
    "D'Hooghe at http://www.freeliterature.org",
    "Department Digital Library. HTML version by Al Haines.",
    "David T. Jones and the Online Distributed Proofreading",
    "Croyle and the Online Distributed Proofreading Team",
    "Craig, Charles Franks, and the Online Distributed",
    "Chuck Greif and the Online Distributed Proofreading Team",
    "Children's Digital Library.)",
    "Charles Franks, and the Online Distributed Proofreading",
    "Charles Franks, and the DP Team",
    "Charles Franks and the DP Team",
    "Center, Michigan State University Libraries.",
    "Celnik, monkeyclogs, Sarah Thomson and others) and the",
    "Canada team (http://www.pgdpcanada.net)",
    "by University of California libraries)",
    "by the University of California, Davis, and with special",
    "by the Library of Congress, Manuscript Division.",
    "by the Google Books Library Project (http://books.google.com) and",
    "by the Google Books Library Project (http://books.google.com)",
    "by the Bibliothèque Nationale de France (BnF/Gallica) at",
    "by the Bibliothèque nationale de France",
    "by gallica (Bibliothèque nationale de France) at",
    "by Florida's Publication of Archival, Library & Museum",
    "Brown, and the Project Gutenberg Online Distributed Proofreading Team",
    "Books project.)",
    "Books Library Project (http://books.google.com/)",
    "books.",
    "(BnF/Gallica) (http://gallica.bnf.fr/)",
    "Biodiversity Heritage Library.)",
    "Bidwell, and the Online Distributed Proofreading Team",
    "Bidwell and the Online Distributed Proofreading Team.",
    "Bibliothèque nationale de France (http://www.bnf.fr)",
    "Bibliothèque nationale de France (BnF/Gallica) at http://gallica.bnf.fr.",
    "Bibliotheque nationale de France (BnF/Gallica) at http://gallica.bnf.fr.",
    "(Bibliothèque nationale de France)",
    "Barcelona",
    "available by the University of California, the HathiTrust",
    "available by the Missouri Botanical Garden",
    "available by the Making of America Collection of the University of",
    "available by the Library of Congress)",
    "available by the Internet Archive - University of",
    "available by the Internet Archive, scanned by Google Books",
    "available by The Internet Archive/Canadian Libraries))",
    "available by the Internet Archive.]",
    "available by the Digital & Multimedia Center, Michigan",
    "available by the Digital Media Repository, Archives and Special",
    "available by the Canadian Institute for Historical Microreproductions",
    "available by the Bodleian Libraries, Oxford)",
    "available by the Biblioth que nationale de France (BnF/Gallica) at",
    "available by Kentuckiana Digital Library (http://kdl.kyvl.org/)",
    "available by Internet Archive (http://www.archive.org/index.php)",
    "available by Gallica, Bibliothèque nationale de France.)",
    "available by Bielefeld University.)",
    "available at The Internet Archive)",
    "at The Internet Archive (https://www.archive.org).",
    "at http://dp.rastko.net",
    "at Distributed Proofreaders Canada",
    "Archives nationales du Québec.)",
    "Archive/Canadian Libraries.)",
    "Archive/Canadian Libraries",
    "Archive/American Libraries.",
    "April 2005",
    "Antiquarian Booksellers.",
    "and the University of Florida",
    "and the PG Online Distributed Proofreading Team",
    "and the Online Distributed Proofreading Team. Images",
    "and the Online Distributed Proofreading Team at http://www.pgdp.net.",
    "and the Online Distributed Proofreaders at",
    "and the Distributed Proofreaders Team",
    "and the booksmiths at http://www.eBookForge.net",
    "and Distributed Proofers",
    "and City Library of Cologne (Digital Collection Westerholt).",
    "American Libraries and the Online Distributed Proofreading",
    "American Cookbook Project at Michigan State University",
    "Allen, and the Online Distributed Proofreading Team.",
)))


TEXT_END_MARKERS = frozenset((u(_) for _ in (
    "*** END OF THE PROJECT GUTENBERG",
    "*** END OF THIS PROJECT GUTENBERG",
    "***END OF THE PROJECT GUTENBERG",
    "End of the Project Gutenberg",
    "End of The Project Gutenberg",
    "Ende dieses Project Gutenberg",
    "by Project Gutenberg",
    "End of Project Gutenberg",
    "End of this Project Gutenberg",
    "Ende dieses Projekt Gutenberg",
    "        ***END OF THE PROJECT GUTENBERG",
    "*** END OF THE COPYRIGHTED",
    "End of this is COPYRIGHTED",
    "Ende dieses Etextes ",
    "Ende dieses Project Gutenber",
    "Ende diese Project Gutenberg",
    "**This is a COPYRIGHTED Project Gutenberg Etext, Details Above**",
    "Fin de Project Gutenberg",
    "The Project Gutenberg Etext of ",
    "Ce document fut presente en lecture",
    "Ce document fut présenté en lecture",
    "More information about this book is at the top of this file.",
    "We need your donations more than ever!",
    "END OF PROJECT GUTENBERG",
    " End of the Project Gutenberg",
    " *** END OF THIS PROJECT GUTENBERG",
)))


LEGALESE_START_MARKERS = frozenset((u(_) for _ in (
    "<<THIS ELECTRONIC VERSION OF",
)))


LEGALESE_END_MARKERS = frozenset((u(_) for _ in (
    "SERVICE THAT CHARGES FOR DOWNLOAD",
)))
