# -*- coding: utf-8 -*-
"""Data module that contains strings that mark the start and end of a Project
Gutenberg disclaimer/header."""


TEXT_START_MARKERS = frozenset((
    ur"*END*THE SMALL PRINT",
    ur"*** START OF THE PROJECT GUTENBERG",
    ur"*** START OF THIS PROJECT GUTENBERG",
    ur"This etext was prepared by",
    ur"E-text prepared by",
    ur"Produced by",
    ur"Distributed Proofreading Team",
    ur"*END THE SMALL PRINT",
    ur"***START OF THE PROJECT GUTENBERG",
    ur"This etext was produced by",
    ur"*** START OF THE COPYRIGHTED",
    ur"The Project Gutenberg",
    ur"http://gutenberg.spiegel.de/ erreichbar.",
    ur"Project Runeberg publishes",
    ur"Beginning of this Project Gutenberg",
    ur"Project Gutenberg Online Distributed",
    ur"Gutenberg Online Distributed",
    ur"the Project Gutenberg Online Distributed",
    ur"Project Gutenberg TEI",
    ur"This eBook was prepared by",
    ur"http://gutenberg2000.de erreichbar.",
    ur"This Etext was prepared by",
    ur"Gutenberg Distributed Proofreaders",
    ur"the Project Gutenberg Online Distributed Proofreading Team",
    ur"**The Project Gutenberg",
    ur"*SMALL PRINT!",
    ur"More information about this book is at the top of this file.",
    ur"tells you about restrictions in how the file may be used.",
    ur"l'authorization à les utilizer pour preparer ce texte.",
    ur"of the etext through OCR.",
    ur"*****These eBooks Were Prepared By Thousands of Volunteers!*****",
    ur"SERVICE THAT CHARGES FOR DOWNLOAD",
    ur"We need your donations more than ever!",
    ur" *** START OF THIS PROJECT GUTENBERG",
    ur"****     SMALL PRINT!",
))


TEXT_END_MARKERS = frozenset((
    ur"*** END OF THE PROJECT GUTENBERG",
    ur"*** END OF THIS PROJECT GUTENBERG",
    ur"***END OF THE PROJECT GUTENBERG",
    ur"End of the Project Gutenberg",
    ur"End of The Project Gutenberg",
    ur"Ende dieses Project Gutenberg",
    ur"by Project Gutenberg",
    ur"End of Project Gutenberg",
    ur"End of this Project Gutenberg",
    ur"Ende dieses Projekt Gutenberg",
    ur"        ***END OF THE PROJECT GUTENBERG",
    ur"*** END OF THE COPYRIGHTED",
    ur"End of this is COPYRIGHTED",
    ur"Ende dieses Etextes ",
    ur"Ende dieses Project Gutenber",
    ur"Ende diese Project Gutenberg",
    ur"**This is a COPYRIGHTED Project Gutenberg Etext, Details Above**",
    ur"Fin de Project Gutenberg",
    ur"The Project Gutenberg Etext of ",
    ur"Ce document fut presente en lecture",
    ur"Ce document fut présenté en lecture",
    ur"More information about this book is at the top of this file.",
    ur"We need your donations more than ever!",
    ur"<<THIS ELECTRONIC VERSION OF",
    ur"END OF PROJECT GUTENBERG",
    ur" End of the Project Gutenberg",
    ur" *** END OF THIS PROJECT GUTENBERG",
))
